// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a15t-cpg236-2I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.390000,HLS_SYN_LAT=9,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=182,HLS_SYN_LUT=259,HLS_VERSION=2025_1}" *)

module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        A_address1,
        A_ce1,
        A_q1,
        B_address0,
        B_ce0,
        B_q0,
        B_address1,
        B_ce1,
        B_q1,
        AB_address0,
        AB_ce0,
        AB_we0,
        AB_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] A_address0;
output   A_ce0;
input  [7:0] A_q0;
output  [1:0] A_address1;
output   A_ce1;
input  [7:0] A_q1;
output  [1:0] B_address0;
output   B_ce0;
input  [7:0] B_q0;
output  [1:0] B_address1;
output   B_ce1;
input  [7:0] B_q1;
output  [1:0] AB_address0;
output   AB_ce0;
output   AB_we0;
output  [15:0] AB_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln9_fu_265_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] select_ln9_fu_167_p3;
reg   [1:0] select_ln9_reg_345;
wire    ap_block_pp0_stage0_11001;
reg   [1:0] select_ln9_reg_345_pp0_iter1_reg;
reg   [1:0] select_ln9_reg_345_pp0_iter2_reg;
reg   [1:0] select_ln9_reg_345_pp0_iter3_reg;
wire   [1:0] empty_4_fu_187_p2;
reg   [1:0] empty_4_reg_350;
reg   [1:0] empty_4_reg_350_pp0_iter1_reg;
reg   [1:0] empty_4_reg_350_pp0_iter2_reg;
reg   [1:0] empty_4_reg_350_pp0_iter3_reg;
wire   [0:0] icmp_ln11_fu_259_p2;
reg   [0:0] icmp_ln11_reg_375;
reg   [0:0] icmp_ln9_reg_380;
reg   [7:0] A_load_1_reg_389;
reg  signed [7:0] A_load_1_reg_389_pp0_iter2_reg;
reg   [7:0] B_load_1_reg_399;
reg  signed [7:0] B_load_1_reg_399_pp0_iter2_reg;
wire  signed [15:0] mul_ln15_fu_300_p2;
reg   [0:0] ap_phi_mux_icmp_ln114_phi_fu_130_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_cast_fu_193_p1;
wire   [63:0] tmp_1_cast_fu_206_p1;
wire   [63:0] zext_ln11_fu_211_p1;
wire   [63:0] zext_ln15_fu_242_p1;
wire   [63:0] zext_ln17_fu_310_p1;
reg   [1:0] indvar_flatten1_fu_52;
wire   [1:0] add_ln9_1_fu_253_p2;
reg   [1:0] ap_sig_allocacmp_indvar_flatten1_load;
reg   [1:0] i2_fu_56;
wire   [1:0] i_fu_175_p3;
reg   [1:0] ap_sig_allocacmp_i2_load;
reg   [1:0] j3_fu_60;
wire   [1:0] j_fu_247_p2;
reg   [1:0] ap_sig_allocacmp_j3_load;
reg    A_ce1_local;
reg    A_ce0_local;
reg    B_ce1_local;
reg    B_ce0_local;
reg    AB_we0_local;
wire  signed [15:0] grp_fu_315_p3;
reg    AB_ce0_local;
wire   [1:0] add_ln9_fu_161_p2;
wire   [0:0] empty_fu_183_p1;
wire   [1:0] tmp_1_fu_198_p3;
wire   [0:0] bit_sel_fu_216_p3;
wire   [0:0] xor_ln15_fu_224_p2;
wire   [0:0] trunc_ln15_fu_230_p1;
wire   [1:0] add_ln15_1_fu_234_p3;
wire   [1:0] add_ln17_fu_306_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_329;
reg    ap_condition_106;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 indvar_flatten1_fu_52 = 2'd0;
#0 i2_fu_56 = 2'd0;
#0 j3_fu_60 = 2'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U1(
    .din0(B_load_1_reg_399_pp0_iter2_reg),
    .din1(A_load_1_reg_389_pp0_iter2_reg),
    .dout(mul_ln15_fu_300_p2)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(B_q1),
    .din1(A_q1),
    .din2(mul_ln15_fu_300_p2),
    .ce(1'b1),
    .dout(grp_fu_315_p3)
);

matrix_mult_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_106)) begin
        i2_fu_56 <= i_fu_175_p3;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_106)) begin
    indvar_flatten1_fu_52 <= add_ln9_1_fu_253_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_106)) begin
    j3_fu_60 <= j_fu_247_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_load_1_reg_389 <= A_q0;
        B_load_1_reg_399 <= B_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        A_load_1_reg_389_pp0_iter2_reg <= A_load_1_reg_389;
        B_load_1_reg_399_pp0_iter2_reg <= B_load_1_reg_399;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        empty_4_reg_350_pp0_iter2_reg <= empty_4_reg_350_pp0_iter1_reg;
        empty_4_reg_350_pp0_iter3_reg <= empty_4_reg_350_pp0_iter2_reg;
        select_ln9_reg_345_pp0_iter2_reg <= select_ln9_reg_345_pp0_iter1_reg;
        select_ln9_reg_345_pp0_iter3_reg <= select_ln9_reg_345_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_4_reg_350 <= empty_4_fu_187_p2;
        empty_4_reg_350_pp0_iter1_reg <= empty_4_reg_350;
        icmp_ln9_reg_380 <= icmp_ln9_fu_265_p2;
        select_ln9_reg_345 <= select_ln9_fu_167_p3;
        select_ln9_reg_345_pp0_iter1_reg <= select_ln9_reg_345;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln11_reg_375 <= icmp_ln11_fu_259_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        AB_ce0_local = 1'b1;
    end else begin
        AB_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        AB_we0_local = 1'b1;
    end else begin
        AB_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce1_local = 1'b1;
    end else begin
        A_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_ce0_local = 1'b1;
    end else begin
        B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_ce1_local = 1'b1;
    end else begin
        B_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln9_fu_265_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_329)) begin
            ap_phi_mux_icmp_ln114_phi_fu_130_p4 = icmp_ln11_reg_375;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln114_phi_fu_130_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln114_phi_fu_130_p4 = icmp_ln11_reg_375;
        end
    end else begin
        ap_phi_mux_icmp_ln114_phi_fu_130_p4 = icmp_ln11_reg_375;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i2_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i2_load = i2_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten1_load = 2'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten1_load = indvar_flatten1_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j3_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j3_load = j3_fu_60;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AB_address0 = zext_ln17_fu_310_p1;

assign AB_ce0 = AB_ce0_local;

assign AB_d0 = grp_fu_315_p3;

assign AB_we0 = AB_we0_local;

assign A_address0 = tmp_1_cast_fu_206_p1;

assign A_address1 = tmp_cast_fu_193_p1;

assign A_ce0 = A_ce0_local;

assign A_ce1 = A_ce1_local;

assign B_address0 = zext_ln15_fu_242_p1;

assign B_address1 = zext_ln11_fu_211_p1;

assign B_ce0 = B_ce0_local;

assign B_ce1 = B_ce1_local;

assign add_ln15_1_fu_234_p3 = {{xor_ln15_fu_224_p2}, {trunc_ln15_fu_230_p1}};

assign add_ln17_fu_306_p2 = (empty_4_reg_350_pp0_iter3_reg + select_ln9_reg_345_pp0_iter3_reg);

assign add_ln9_1_fu_253_p2 = (ap_sig_allocacmp_indvar_flatten1_load + 2'd1);

assign add_ln9_fu_161_p2 = (ap_sig_allocacmp_i2_load + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_106 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_329 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln9_reg_380 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bit_sel_fu_216_p3 = select_ln9_fu_167_p3[2'd1];

assign empty_4_fu_187_p2 = i_fu_175_p3 << 2'd1;

assign empty_fu_183_p1 = i_fu_175_p3[0:0];

assign i_fu_175_p3 = ((ap_phi_mux_icmp_ln114_phi_fu_130_p4[0:0] == 1'b1) ? add_ln9_fu_161_p2 : ap_sig_allocacmp_i2_load);

assign icmp_ln11_fu_259_p2 = ((j_fu_247_p2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_265_p2 = ((ap_sig_allocacmp_indvar_flatten1_load == 2'd3) ? 1'b1 : 1'b0);

assign j_fu_247_p2 = (select_ln9_fu_167_p3 + 2'd1);

assign select_ln9_fu_167_p3 = ((ap_phi_mux_icmp_ln114_phi_fu_130_p4[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j3_load);

assign tmp_1_cast_fu_206_p1 = tmp_1_fu_198_p3;

assign tmp_1_fu_198_p3 = {{empty_fu_183_p1}, {1'd1}};

assign tmp_cast_fu_193_p1 = empty_4_fu_187_p2;

assign trunc_ln15_fu_230_p1 = select_ln9_fu_167_p3[0:0];

assign xor_ln15_fu_224_p2 = (bit_sel_fu_216_p3 ^ 1'd1);

assign zext_ln11_fu_211_p1 = select_ln9_fu_167_p3;

assign zext_ln15_fu_242_p1 = add_ln15_1_fu_234_p3;

assign zext_ln17_fu_310_p1 = add_ln17_fu_306_p2;

endmodule //matrix_mult
