-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult_Loop_row_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    A_ce1 : OUT STD_LOGIC;
    A_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    B_ce0 : OUT STD_LOGIC;
    B_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    B_ce1 : OUT STD_LOGIC;
    B_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    AB_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    AB_ce0 : OUT STD_LOGIC;
    AB_we0 : OUT STD_LOGIC;
    AB_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matrix_mult_Loop_row_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln9_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln9_fu_169_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln9_reg_323 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln9_reg_323_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln9_reg_323_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_9_fu_189_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_9_reg_328 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_9_reg_328_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_9_reg_328_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln11_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_353 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_358 : STD_LOGIC_VECTOR (0 downto 0);
    signal A_load_reg_362 : STD_LOGIC_VECTOR (31 downto 0);
    signal A_load_1_reg_367 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_load_reg_372 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_load_1_reg_377 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln16_fu_131_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln16_reg_382 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln16_1_fu_135_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln16_1_reg_387 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_icmp_ln114_phi_fu_124_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_cast_fu_195_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_cast_fu_208_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_fu_213_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_fu_244_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln18_fu_292_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_46 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln9_1_fu_255_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_indvar_flatten1_load : STD_LOGIC_VECTOR (1 downto 0);
    signal i2_fu_50 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal i_fu_177_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_i2_load : STD_LOGIC_VECTOR (1 downto 0);
    signal j3_fu_54 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal j_fu_249_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_j3_load : STD_LOGIC_VECTOR (1 downto 0);
    signal A_ce1_local : STD_LOGIC;
    signal A_ce0_local : STD_LOGIC;
    signal B_ce1_local : STD_LOGIC;
    signal B_ce0_local : STD_LOGIC;
    signal AB_we0_local : STD_LOGIC;
    signal ABij_fu_297_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal AB_ce0_local : STD_LOGIC;
    signal add_ln9_fu_163_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_fu_185_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_200_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal bit_sel_fu_218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln16_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln16_fu_232_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln_fu_236_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln18_fu_288_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_312 : BOOLEAN;
    signal ap_condition_108 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matrix_mult_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_1_1_U1 : component matrix_mult_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => B_load_1_reg_377,
        din1 => A_load_1_reg_367,
        dout => mul_ln16_fu_131_p2);

    mul_32s_32s_32_1_1_U2 : component matrix_mult_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => B_load_reg_372,
        din1 => A_load_reg_362,
        dout => mul_ln16_1_fu_135_p2);

    flow_control_loop_pipe_U : component matrix_mult_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    i2_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_108)) then
                i2_fu_50 <= i_fu_177_p3;
            end if;
        end if;
    end process;

    indvar_flatten1_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_108)) then
                indvar_flatten1_fu_46 <= add_ln9_1_fu_255_p2;
            end if;
        end if;
    end process;

    j3_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_108)) then
                j3_fu_54 <= j_fu_249_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                A_load_1_reg_367 <= A_q0;
                A_load_reg_362 <= A_q1;
                B_load_1_reg_377 <= B_q0;
                B_load_reg_372 <= B_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                empty_9_reg_328 <= empty_9_fu_189_p2;
                empty_9_reg_328_pp0_iter1_reg <= empty_9_reg_328;
                icmp_ln9_reg_358 <= icmp_ln9_fu_267_p2;
                select_ln9_reg_323 <= select_ln9_fu_169_p3;
                select_ln9_reg_323_pp0_iter1_reg <= select_ln9_reg_323;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                empty_9_reg_328_pp0_iter2_reg <= empty_9_reg_328_pp0_iter1_reg;
                mul_ln16_1_reg_387 <= mul_ln16_1_fu_135_p2;
                mul_ln16_reg_382 <= mul_ln16_fu_131_p2;
                select_ln9_reg_323_pp0_iter2_reg <= select_ln9_reg_323_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln11_reg_353 <= icmp_ln11_fu_261_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    AB_address0 <= zext_ln18_fu_292_p1(2 - 1 downto 0);
    AB_ce0 <= AB_ce0_local;

    AB_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            AB_ce0_local <= ap_const_logic_1;
        else 
            AB_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    AB_d0 <= ABij_fu_297_p2;
    AB_we0 <= AB_we0_local;

    AB_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            AB_we0_local <= ap_const_logic_1;
        else 
            AB_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    ABij_fu_297_p2 <= std_logic_vector(unsigned(mul_ln16_reg_382) + unsigned(mul_ln16_1_reg_387));
    A_address0 <= tmp_1_cast_fu_208_p1(2 - 1 downto 0);
    A_address1 <= tmp_cast_fu_195_p1(2 - 1 downto 0);
    A_ce0 <= A_ce0_local;

    A_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_ce0_local <= ap_const_logic_1;
        else 
            A_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_ce1 <= A_ce1_local;

    A_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_ce1_local <= ap_const_logic_1;
        else 
            A_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_address0 <= zext_ln16_fu_244_p1(2 - 1 downto 0);
    B_address1 <= zext_ln11_fu_213_p1(2 - 1 downto 0);
    B_ce0 <= B_ce0_local;

    B_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            B_ce0_local <= ap_const_logic_1;
        else 
            B_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_ce1 <= B_ce1_local;

    B_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            B_ce1_local <= ap_const_logic_1;
        else 
            B_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln18_fu_288_p2 <= std_logic_vector(unsigned(empty_9_reg_328_pp0_iter2_reg) + unsigned(select_ln9_reg_323_pp0_iter2_reg));
    add_ln9_1_fu_255_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten1_load) + unsigned(ap_const_lv2_1));
    add_ln9_fu_163_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i2_load) + unsigned(ap_const_lv2_1));
    add_ln_fu_236_p3 <= (xor_ln16_fu_226_p2 & trunc_ln16_fu_232_p1);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_condition_108_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_108 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_312_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln9_reg_358, ap_block_pp0_stage0)
    begin
                ap_condition_312 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln9_reg_358 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln9_fu_267_p2, ap_start_int)
    begin
        if (((icmp_ln9_fu_267_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_icmp_ln114_phi_fu_124_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln11_reg_353, ap_loop_init, ap_condition_312)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_312)) then 
                ap_phi_mux_icmp_ln114_phi_fu_124_p4 <= icmp_ln11_reg_353;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln114_phi_fu_124_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln114_phi_fu_124_p4 <= icmp_ln11_reg_353;
            end if;
        else 
            ap_phi_mux_icmp_ln114_phi_fu_124_p4 <= icmp_ln11_reg_353;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, i2_fu_50, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i2_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_i2_load <= i2_fu_50;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten1_fu_46, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten1_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_indvar_flatten1_load <= indvar_flatten1_fu_46;
        end if; 
    end process;


    ap_sig_allocacmp_j3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, j3_fu_54, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j3_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_j3_load <= j3_fu_54;
        end if; 
    end process;

    bit_sel_fu_218_p3 <= select_ln9_fu_169_p3(1 downto 1);
    empty_9_fu_189_p2 <= std_logic_vector(shift_left(unsigned(i_fu_177_p3),to_integer(unsigned('0' & ap_const_lv2_1(2-1 downto 0)))));
    empty_fu_185_p1 <= i_fu_177_p3(1 - 1 downto 0);
    i_fu_177_p3 <= 
        add_ln9_fu_163_p2 when (ap_phi_mux_icmp_ln114_phi_fu_124_p4(0) = '1') else 
        ap_sig_allocacmp_i2_load;
    icmp_ln11_fu_261_p2 <= "1" when (j_fu_249_p2 = ap_const_lv2_2) else "0";
    icmp_ln9_fu_267_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten1_load = ap_const_lv2_3) else "0";
    j_fu_249_p2 <= std_logic_vector(unsigned(select_ln9_fu_169_p3) + unsigned(ap_const_lv2_1));
    select_ln9_fu_169_p3 <= 
        ap_const_lv2_0 when (ap_phi_mux_icmp_ln114_phi_fu_124_p4(0) = '1') else 
        ap_sig_allocacmp_j3_load;
    tmp_1_cast_fu_208_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_200_p3),64));
    tmp_1_fu_200_p3 <= (empty_fu_185_p1 & ap_const_lv1_1);
    tmp_cast_fu_195_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_9_fu_189_p2),64));
    trunc_ln16_fu_232_p1 <= select_ln9_fu_169_p3(1 - 1 downto 0);
    xor_ln16_fu_226_p2 <= (bit_sel_fu_218_p3 xor ap_const_lv1_1);
    zext_ln11_fu_213_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln9_fu_169_p3),64));
    zext_ln16_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_236_p3),64));
    zext_ln18_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln18_fu_288_p2),64));
end behav;
