// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a15t-cpg236-2I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.880000,HLS_SYN_LAT=8,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=398,HLS_SYN_LUT=259,HLS_VERSION=2025_1}" *)

module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        B_address0,
        B_ce0,
        B_q0,
        B_address1,
        B_ce1,
        B_q1,
        AB_address0,
        AB_ce0,
        AB_we0,
        AB_d0,
        AB_address1,
        AB_ce1,
        AB_we1,
        AB_d1
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] A_address0;
output   A_ce0;
input  [63:0] A_q0;
output  [0:0] B_address0;
output   B_ce0;
input  [63:0] B_q0;
output  [0:0] B_address1;
output   B_ce1;
input  [63:0] B_q1;
output  [1:0] AB_address0;
output   AB_ce0;
output   AB_we0;
output  [31:0] AB_d0;
output  [1:0] AB_address1;
output   AB_ce1;
output   AB_we1;
output  [31:0] AB_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] trunc_ln15_fu_71_p1;
reg   [31:0] trunc_ln15_reg_109;
wire    ap_CS_fsm_state2;
reg   [31:0] tmp_1_reg_114;
wire   [31:0] trunc_ln15_1_fu_85_p1;
reg   [31:0] trunc_ln15_1_reg_119;
reg   [31:0] tmp_3_reg_124;
wire    grp_matrix_mult_Pipeline_row_fu_59_ap_start;
wire    grp_matrix_mult_Pipeline_row_fu_59_ap_done;
wire    grp_matrix_mult_Pipeline_row_fu_59_ap_idle;
wire    grp_matrix_mult_Pipeline_row_fu_59_ap_ready;
wire   [1:0] grp_matrix_mult_Pipeline_row_fu_59_AB_address0;
wire    grp_matrix_mult_Pipeline_row_fu_59_AB_ce0;
wire    grp_matrix_mult_Pipeline_row_fu_59_AB_we0;
wire   [31:0] grp_matrix_mult_Pipeline_row_fu_59_AB_d0;
wire   [1:0] grp_matrix_mult_Pipeline_row_fu_59_AB_address1;
wire    grp_matrix_mult_Pipeline_row_fu_59_AB_ce1;
wire    grp_matrix_mult_Pipeline_row_fu_59_AB_we1;
wire   [31:0] grp_matrix_mult_Pipeline_row_fu_59_AB_d1;
wire   [0:0] grp_matrix_mult_Pipeline_row_fu_59_A_address0;
wire    grp_matrix_mult_Pipeline_row_fu_59_A_ce0;
reg    grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    B_ce1_local;
reg    B_ce0_local;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg = 1'b0;
end

matrix_mult_matrix_mult_Pipeline_row grp_matrix_mult_Pipeline_row_fu_59(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_matrix_mult_Pipeline_row_fu_59_ap_start),
    .ap_done(grp_matrix_mult_Pipeline_row_fu_59_ap_done),
    .ap_idle(grp_matrix_mult_Pipeline_row_fu_59_ap_idle),
    .ap_ready(grp_matrix_mult_Pipeline_row_fu_59_ap_ready),
    .AB_address0(grp_matrix_mult_Pipeline_row_fu_59_AB_address0),
    .AB_ce0(grp_matrix_mult_Pipeline_row_fu_59_AB_ce0),
    .AB_we0(grp_matrix_mult_Pipeline_row_fu_59_AB_we0),
    .AB_d0(grp_matrix_mult_Pipeline_row_fu_59_AB_d0),
    .AB_address1(grp_matrix_mult_Pipeline_row_fu_59_AB_address1),
    .AB_ce1(grp_matrix_mult_Pipeline_row_fu_59_AB_ce1),
    .AB_we1(grp_matrix_mult_Pipeline_row_fu_59_AB_we1),
    .AB_d1(grp_matrix_mult_Pipeline_row_fu_59_AB_d1),
    .A_address0(grp_matrix_mult_Pipeline_row_fu_59_A_address0),
    .A_ce0(grp_matrix_mult_Pipeline_row_fu_59_A_ce0),
    .A_q0(A_q0),
    .tmp_1(tmp_1_reg_114),
    .empty_3(trunc_ln15_reg_109),
    .tmp_3(tmp_3_reg_124),
    .empty(trunc_ln15_1_reg_119)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg <= 1'b1;
        end else if ((grp_matrix_mult_Pipeline_row_fu_59_ap_ready == 1'b1)) begin
            grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_1_reg_114 <= {{B_q1[63:32]}};
        tmp_3_reg_124 <= {{B_q0[63:32]}};
        trunc_ln15_1_reg_119 <= trunc_ln15_1_fu_85_p1;
        trunc_ln15_reg_109 <= trunc_ln15_fu_71_p1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        B_ce0_local = 1'b1;
    end else begin
        B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        B_ce1_local = 1'b1;
    end else begin
        B_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_matrix_mult_Pipeline_row_fu_59_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_matrix_mult_Pipeline_row_fu_59_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_matrix_mult_Pipeline_row_fu_59_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_matrix_mult_Pipeline_row_fu_59_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AB_address0 = grp_matrix_mult_Pipeline_row_fu_59_AB_address0;

assign AB_address1 = grp_matrix_mult_Pipeline_row_fu_59_AB_address1;

assign AB_ce0 = grp_matrix_mult_Pipeline_row_fu_59_AB_ce0;

assign AB_ce1 = grp_matrix_mult_Pipeline_row_fu_59_AB_ce1;

assign AB_d0 = grp_matrix_mult_Pipeline_row_fu_59_AB_d0;

assign AB_d1 = grp_matrix_mult_Pipeline_row_fu_59_AB_d1;

assign AB_we0 = grp_matrix_mult_Pipeline_row_fu_59_AB_we0;

assign AB_we1 = grp_matrix_mult_Pipeline_row_fu_59_AB_we1;

assign A_address0 = grp_matrix_mult_Pipeline_row_fu_59_A_address0;

assign A_ce0 = grp_matrix_mult_Pipeline_row_fu_59_A_ce0;

assign B_address0 = 64'd1;

assign B_address1 = 64'd0;

assign B_ce0 = B_ce0_local;

assign B_ce1 = B_ce1_local;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign grp_matrix_mult_Pipeline_row_fu_59_ap_start = grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg;

assign trunc_ln15_1_fu_85_p1 = B_q0[31:0];

assign trunc_ln15_fu_71_p1 = B_q1[31:0];

endmodule //matrix_mult
