// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matrix_mult_Loop_row_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        A_address1,
        A_ce1,
        A_q1,
        B_address0,
        B_ce0,
        B_q0,
        B_address1,
        B_ce1,
        B_q1,
        AB_address0,
        AB_ce0,
        AB_we0,
        AB_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [1:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [1:0] A_address1;
output   A_ce1;
input  [31:0] A_q1;
output  [1:0] B_address0;
output   B_ce0;
input  [31:0] B_q0;
output  [1:0] B_address1;
output   B_ce1;
input  [31:0] B_q1;
output  [1:0] AB_address0;
output   AB_ce0;
output   AB_we0;
output  [31:0] AB_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln9_fu_267_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] select_ln9_fu_169_p3;
reg   [1:0] select_ln9_reg_323;
reg    ap_block_pp0_stage0_11001;
reg   [1:0] select_ln9_reg_323_pp0_iter1_reg;
reg   [1:0] select_ln9_reg_323_pp0_iter2_reg;
wire   [1:0] empty_9_fu_189_p2;
reg   [1:0] empty_9_reg_328;
reg   [1:0] empty_9_reg_328_pp0_iter1_reg;
reg   [1:0] empty_9_reg_328_pp0_iter2_reg;
wire   [0:0] icmp_ln11_fu_261_p2;
reg   [0:0] icmp_ln11_reg_353;
reg   [0:0] icmp_ln9_reg_358;
reg  signed [31:0] A_load_reg_362;
reg  signed [31:0] A_load_1_reg_367;
reg  signed [31:0] B_load_reg_372;
reg  signed [31:0] B_load_1_reg_377;
wire   [31:0] mul_ln16_fu_131_p2;
reg   [31:0] mul_ln16_reg_382;
wire   [31:0] mul_ln16_1_fu_135_p2;
reg   [31:0] mul_ln16_1_reg_387;
reg   [0:0] ap_phi_mux_icmp_ln114_phi_fu_124_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_cast_fu_195_p1;
wire   [63:0] tmp_1_cast_fu_208_p1;
wire   [63:0] zext_ln11_fu_213_p1;
wire   [63:0] zext_ln16_fu_244_p1;
wire   [63:0] zext_ln18_fu_292_p1;
reg   [1:0] indvar_flatten1_fu_46;
wire   [1:0] add_ln9_1_fu_255_p2;
reg   [1:0] ap_sig_allocacmp_indvar_flatten1_load;
reg   [1:0] i2_fu_50;
wire   [1:0] i_fu_177_p3;
reg   [1:0] ap_sig_allocacmp_i2_load;
reg   [1:0] j3_fu_54;
wire   [1:0] j_fu_249_p2;
reg   [1:0] ap_sig_allocacmp_j3_load;
reg    A_ce1_local;
reg    A_ce0_local;
reg    B_ce1_local;
reg    B_ce0_local;
reg    AB_we0_local;
wire   [31:0] ABij_fu_297_p2;
reg    AB_ce0_local;
wire   [1:0] add_ln9_fu_163_p2;
wire   [0:0] empty_fu_185_p1;
wire   [1:0] tmp_1_fu_200_p3;
wire   [0:0] bit_sel_fu_218_p3;
wire   [0:0] xor_ln16_fu_226_p2;
wire   [0:0] trunc_ln16_fu_232_p1;
wire   [1:0] add_ln_fu_236_p3;
wire   [1:0] add_ln18_fu_288_p2;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_312;
reg    ap_condition_108;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 indvar_flatten1_fu_46 = 2'd0;
#0 i2_fu_50 = 2'd0;
#0 j3_fu_54 = 2'd0;
end

matrix_mult_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U1(
    .din0(B_load_1_reg_377),
    .din1(A_load_1_reg_367),
    .dout(mul_ln16_fu_131_p2)
);

matrix_mult_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U2(
    .din0(B_load_reg_372),
    .din1(A_load_reg_362),
    .dout(mul_ln16_1_fu_135_p2)
);

matrix_mult_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_108)) begin
        i2_fu_50 <= i_fu_177_p3;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_108)) begin
    indvar_flatten1_fu_46 <= add_ln9_1_fu_255_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_108)) begin
    j3_fu_54 <= j_fu_249_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_load_1_reg_367 <= A_q0;
        A_load_reg_362 <= A_q1;
        B_load_1_reg_377 <= B_q0;
        B_load_reg_372 <= B_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_9_reg_328 <= empty_9_fu_189_p2;
        empty_9_reg_328_pp0_iter1_reg <= empty_9_reg_328;
        icmp_ln9_reg_358 <= icmp_ln9_fu_267_p2;
        select_ln9_reg_323 <= select_ln9_fu_169_p3;
        select_ln9_reg_323_pp0_iter1_reg <= select_ln9_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        empty_9_reg_328_pp0_iter2_reg <= empty_9_reg_328_pp0_iter1_reg;
        mul_ln16_1_reg_387 <= mul_ln16_1_fu_135_p2;
        mul_ln16_reg_382 <= mul_ln16_fu_131_p2;
        select_ln9_reg_323_pp0_iter2_reg <= select_ln9_reg_323_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln11_reg_353 <= icmp_ln11_fu_261_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        AB_ce0_local = 1'b1;
    end else begin
        AB_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        AB_we0_local = 1'b1;
    end else begin
        AB_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce1_local = 1'b1;
    end else begin
        A_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_ce0_local = 1'b1;
    end else begin
        B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_ce1_local = 1'b1;
    end else begin
        B_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln9_fu_267_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_312)) begin
            ap_phi_mux_icmp_ln114_phi_fu_124_p4 = icmp_ln11_reg_353;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln114_phi_fu_124_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln114_phi_fu_124_p4 = icmp_ln11_reg_353;
        end
    end else begin
        ap_phi_mux_icmp_ln114_phi_fu_124_p4 = icmp_ln11_reg_353;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i2_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i2_load = i2_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten1_load = 2'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten1_load = indvar_flatten1_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j3_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j3_load = j3_fu_54;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AB_address0 = zext_ln18_fu_292_p1;

assign AB_ce0 = AB_ce0_local;

assign AB_d0 = ABij_fu_297_p2;

assign AB_we0 = AB_we0_local;

assign ABij_fu_297_p2 = (mul_ln16_reg_382 + mul_ln16_1_reg_387);

assign A_address0 = tmp_1_cast_fu_208_p1;

assign A_address1 = tmp_cast_fu_195_p1;

assign A_ce0 = A_ce0_local;

assign A_ce1 = A_ce1_local;

assign B_address0 = zext_ln16_fu_244_p1;

assign B_address1 = zext_ln11_fu_213_p1;

assign B_ce0 = B_ce0_local;

assign B_ce1 = B_ce1_local;

assign add_ln18_fu_288_p2 = (empty_9_reg_328_pp0_iter2_reg + select_ln9_reg_323_pp0_iter2_reg);

assign add_ln9_1_fu_255_p2 = (ap_sig_allocacmp_indvar_flatten1_load + 2'd1);

assign add_ln9_fu_163_p2 = (ap_sig_allocacmp_i2_load + 2'd1);

assign add_ln_fu_236_p3 = {{xor_ln16_fu_226_p2}, {trunc_ln16_fu_232_p1}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_condition_108 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_312 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln9_reg_358 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bit_sel_fu_218_p3 = select_ln9_fu_169_p3[2'd1];

assign empty_9_fu_189_p2 = i_fu_177_p3 << 2'd1;

assign empty_fu_185_p1 = i_fu_177_p3[0:0];

assign i_fu_177_p3 = ((ap_phi_mux_icmp_ln114_phi_fu_124_p4[0:0] == 1'b1) ? add_ln9_fu_163_p2 : ap_sig_allocacmp_i2_load);

assign icmp_ln11_fu_261_p2 = ((j_fu_249_p2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_267_p2 = ((ap_sig_allocacmp_indvar_flatten1_load == 2'd3) ? 1'b1 : 1'b0);

assign j_fu_249_p2 = (select_ln9_fu_169_p3 + 2'd1);

assign select_ln9_fu_169_p3 = ((ap_phi_mux_icmp_ln114_phi_fu_124_p4[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j3_load);

assign tmp_1_cast_fu_208_p1 = tmp_1_fu_200_p3;

assign tmp_1_fu_200_p3 = {{empty_fu_185_p1}, {1'd1}};

assign tmp_cast_fu_195_p1 = empty_9_fu_189_p2;

assign trunc_ln16_fu_232_p1 = select_ln9_fu_169_p3[0:0];

assign xor_ln16_fu_226_p2 = (bit_sel_fu_218_p3 ^ 1'd1);

assign zext_ln11_fu_213_p1 = select_ln9_fu_169_p3;

assign zext_ln16_fu_244_p1 = add_ln_fu_236_p3;

assign zext_ln18_fu_292_p1 = add_ln18_fu_288_p2;

endmodule //matrix_mult_Loop_row_proc
