// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a15t-cpg236-2I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.880000,HLS_SYN_LAT=8,HLS_SYN_TPT=4,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=340,HLS_SYN_LUT=301,HLS_VERSION=2025_1}" *)

module matrix_mult (
        A_address0,
        A_ce0,
        A_d0,
        A_q0,
        A_we0,
        A_address1,
        A_ce1,
        A_d1,
        A_q1,
        A_we1,
        B_address0,
        B_ce0,
        B_d0,
        B_q0,
        B_we0,
        B_address1,
        B_ce1,
        B_d1,
        B_q1,
        B_we1,
        AB_address0,
        AB_ce0,
        AB_d0,
        AB_q0,
        AB_we0,
        AB_address1,
        AB_ce1,
        AB_d1,
        AB_q1,
        AB_we1,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


output  [1:0] A_address0;
output   A_ce0;
output  [31:0] A_d0;
input  [31:0] A_q0;
output   A_we0;
output  [1:0] A_address1;
output   A_ce1;
output  [31:0] A_d1;
input  [31:0] A_q1;
output   A_we1;
output  [1:0] B_address0;
output   B_ce0;
output  [31:0] B_d0;
input  [31:0] B_q0;
output   B_we0;
output  [1:0] B_address1;
output   B_ce1;
output  [31:0] B_d1;
input  [31:0] B_q1;
output   B_we1;
output  [1:0] AB_address0;
output   AB_ce0;
output  [31:0] AB_d0;
input  [31:0] AB_q0;
output   AB_we0;
output  [1:0] AB_address1;
output   AB_ce1;
output  [31:0] AB_d1;
input  [31:0] AB_q1;
output   AB_we1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Loop_row_proc_U0_ap_start;
wire    Loop_row_proc_U0_ap_done;
wire    Loop_row_proc_U0_ap_continue;
wire    Loop_row_proc_U0_ap_idle;
wire    Loop_row_proc_U0_ap_ready;
wire   [1:0] Loop_row_proc_U0_A_address0;
wire    Loop_row_proc_U0_A_ce0;
wire   [1:0] Loop_row_proc_U0_A_address1;
wire    Loop_row_proc_U0_A_ce1;
wire   [1:0] Loop_row_proc_U0_B_address0;
wire    Loop_row_proc_U0_B_ce0;
wire   [1:0] Loop_row_proc_U0_B_address1;
wire    Loop_row_proc_U0_B_ce1;
wire   [1:0] Loop_row_proc_U0_AB_address0;
wire    Loop_row_proc_U0_AB_ce0;
wire    Loop_row_proc_U0_AB_we0;
wire   [31:0] Loop_row_proc_U0_AB_d0;

matrix_mult_Loop_row_proc Loop_row_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_row_proc_U0_ap_start),
    .ap_done(Loop_row_proc_U0_ap_done),
    .ap_continue(Loop_row_proc_U0_ap_continue),
    .ap_idle(Loop_row_proc_U0_ap_idle),
    .ap_ready(Loop_row_proc_U0_ap_ready),
    .A_address0(Loop_row_proc_U0_A_address0),
    .A_ce0(Loop_row_proc_U0_A_ce0),
    .A_q0(A_q0),
    .A_address1(Loop_row_proc_U0_A_address1),
    .A_ce1(Loop_row_proc_U0_A_ce1),
    .A_q1(A_q1),
    .B_address0(Loop_row_proc_U0_B_address0),
    .B_ce0(Loop_row_proc_U0_B_ce0),
    .B_q0(B_q0),
    .B_address1(Loop_row_proc_U0_B_address1),
    .B_ce1(Loop_row_proc_U0_B_ce1),
    .B_q1(B_q1),
    .AB_address0(Loop_row_proc_U0_AB_address0),
    .AB_ce0(Loop_row_proc_U0_AB_ce0),
    .AB_we0(Loop_row_proc_U0_AB_we0),
    .AB_d0(Loop_row_proc_U0_AB_d0)
);

assign AB_address0 = Loop_row_proc_U0_AB_address0;

assign AB_address1 = 2'd0;

assign AB_ce0 = Loop_row_proc_U0_AB_ce0;

assign AB_ce1 = 1'b0;

assign AB_d0 = Loop_row_proc_U0_AB_d0;

assign AB_d1 = 32'd0;

assign AB_we0 = Loop_row_proc_U0_AB_we0;

assign AB_we1 = 1'b0;

assign A_address0 = Loop_row_proc_U0_A_address0;

assign A_address1 = Loop_row_proc_U0_A_address1;

assign A_ce0 = Loop_row_proc_U0_A_ce0;

assign A_ce1 = Loop_row_proc_U0_A_ce1;

assign A_d0 = 32'd0;

assign A_d1 = 32'd0;

assign A_we0 = 1'b0;

assign A_we1 = 1'b0;

assign B_address0 = Loop_row_proc_U0_B_address0;

assign B_address1 = Loop_row_proc_U0_B_address1;

assign B_ce0 = Loop_row_proc_U0_B_ce0;

assign B_ce1 = Loop_row_proc_U0_B_ce1;

assign B_d0 = 32'd0;

assign B_d1 = 32'd0;

assign B_we0 = 1'b0;

assign B_we1 = 1'b0;

assign Loop_row_proc_U0_ap_continue = 1'b1;

assign Loop_row_proc_U0_ap_start = ap_start;

assign ap_done = Loop_row_proc_U0_ap_done;

assign ap_idle = Loop_row_proc_U0_ap_idle;

assign ap_ready = Loop_row_proc_U0_ap_ready;

endmodule //matrix_mult
