// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matrix_mult_matrix_mult_Pipeline_row (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        AB_address0,
        AB_ce0,
        AB_we0,
        AB_d0,
        AB_address1,
        AB_ce1,
        AB_we1,
        AB_d1,
        A_address0,
        A_ce0,
        A_q0,
        tmp_1,
        empty_3,
        tmp_3,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] AB_address0;
output   AB_ce0;
output   AB_we0;
output  [31:0] AB_d0;
output  [1:0] AB_address1;
output   AB_ce1;
output   AB_we1;
output  [31:0] AB_d1;
output  [0:0] A_address0;
output   A_ce0;
input  [63:0] A_q0;
input  [31:0] tmp_1;
input  [31:0] empty_3;
input  [31:0] tmp_3;
input  [31:0] empty;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_i1_phi_fu_111_p4;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] i1_reg_108;
reg   [0:0] i1_reg_108_pp0_iter1_reg;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] i1_reg_108_pp0_iter2_reg;
wire   [0:0] i_fu_140_p2;
reg   [0:0] i_reg_219;
wire  signed [31:0] trunc_ln15_fu_146_p1;
reg  signed [31:0] trunc_ln15_reg_224;
reg  signed [31:0] tmp_5_reg_230;
wire   [31:0] mul_ln15_fu_119_p2;
reg   [31:0] mul_ln15_reg_236;
wire   [31:0] mul_ln15_1_fu_123_p2;
reg   [31:0] mul_ln15_1_reg_241;
wire   [31:0] mul_ln15_2_fu_127_p2;
reg   [31:0] mul_ln15_2_reg_246;
wire   [31:0] mul_ln15_3_fu_131_p2;
reg   [31:0] mul_ln15_3_reg_251;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln9_fu_135_p1;
wire   [63:0] zext_ln17_fu_166_p1;
wire   [63:0] zext_ln17_1_fu_179_p1;
reg    A_ce0_local;
reg    AB_we1_local;
wire   [31:0] ABij_fu_184_p2;
reg    AB_ce1_local;
reg    AB_we0_local;
wire   [31:0] ABij_1_fu_189_p2;
reg    AB_ce0_local;
wire   [1:0] tmp_6_fu_158_p3;
wire   [1:0] tmp_7_fu_171_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_244;
reg    ap_condition_249;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U1(
    .din0(tmp_5_reg_230),
    .din1(tmp_1),
    .dout(mul_ln15_fu_119_p2)
);

matrix_mult_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U2(
    .din0(trunc_ln15_reg_224),
    .din1(empty_3),
    .dout(mul_ln15_1_fu_123_p2)
);

matrix_mult_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U3(
    .din0(tmp_5_reg_230),
    .din1(tmp_3),
    .dout(mul_ln15_2_fu_127_p2)
);

matrix_mult_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U4(
    .din0(trunc_ln15_reg_224),
    .din1(empty),
    .dout(mul_ln15_3_fu_131_p2)
);

matrix_mult_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_249)) begin
            i1_reg_108 <= i_reg_219;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            i1_reg_108 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i1_reg_108_pp0_iter1_reg <= i1_reg_108;
        tmp_5_reg_230 <= {{A_q0[63:32]}};
        trunc_ln15_reg_224 <= trunc_ln15_fu_146_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        i1_reg_108_pp0_iter2_reg <= i1_reg_108_pp0_iter1_reg;
        mul_ln15_1_reg_241 <= mul_ln15_1_fu_123_p2;
        mul_ln15_2_reg_246 <= mul_ln15_2_fu_127_p2;
        mul_ln15_3_reg_251 <= mul_ln15_3_fu_131_p2;
        mul_ln15_reg_236 <= mul_ln15_fu_119_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_219 <= i_fu_140_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        AB_ce0_local = 1'b1;
    end else begin
        AB_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        AB_ce1_local = 1'b1;
    end else begin
        AB_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        AB_we0_local = 1'b1;
    end else begin
        AB_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        AB_we1_local = 1'b1;
    end else begin
        AB_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_i1_phi_fu_111_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_244)) begin
            ap_phi_mux_i1_phi_fu_111_p4 = i_reg_219;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_i1_phi_fu_111_p4 = 1'd0;
        end else begin
            ap_phi_mux_i1_phi_fu_111_p4 = i1_reg_108;
        end
    end else begin
        ap_phi_mux_i1_phi_fu_111_p4 = i1_reg_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AB_address0 = zext_ln17_1_fu_179_p1;

assign AB_address1 = zext_ln17_fu_166_p1;

assign AB_ce0 = AB_ce0_local;

assign AB_ce1 = AB_ce1_local;

assign AB_d0 = ABij_1_fu_189_p2;

assign AB_d1 = ABij_fu_184_p2;

assign AB_we0 = AB_we0_local;

assign AB_we1 = AB_we1_local;

assign ABij_1_fu_189_p2 = (mul_ln15_2_reg_246 + mul_ln15_3_reg_251);

assign ABij_fu_184_p2 = (mul_ln15_reg_236 + mul_ln15_1_reg_241);

assign A_address0 = zext_ln9_fu_135_p1;

assign A_ce0 = A_ce0_local;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_244 = ((i1_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_249 = ((i1_reg_108 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign i_fu_140_p2 = (ap_phi_mux_i1_phi_fu_111_p4 ^ 1'd1);

assign tmp_6_fu_158_p3 = {{i1_reg_108_pp0_iter2_reg}, {1'd0}};

assign tmp_7_fu_171_p3 = {{i1_reg_108_pp0_iter2_reg}, {1'd1}};

assign trunc_ln15_fu_146_p1 = A_q0[31:0];

assign zext_ln17_1_fu_179_p1 = tmp_7_fu_171_p3;

assign zext_ln17_fu_166_p1 = tmp_6_fu_158_p3;

assign zext_ln9_fu_135_p1 = ap_phi_mux_i1_phi_fu_111_p4;

endmodule //matrix_mult_matrix_mult_Pipeline_row
