-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    A_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_we0 : OUT STD_LOGIC;
    A_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    A_ce1 : OUT STD_LOGIC;
    A_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_we1 : OUT STD_LOGIC;
    B_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    B_ce0 : OUT STD_LOGIC;
    B_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_we0 : OUT STD_LOGIC;
    B_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    B_ce1 : OUT STD_LOGIC;
    B_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_we1 : OUT STD_LOGIC;
    AB_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    AB_ce0 : OUT STD_LOGIC;
    AB_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    AB_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    AB_we0 : OUT STD_LOGIC;
    AB_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    AB_ce1 : OUT STD_LOGIC;
    AB_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    AB_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    AB_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of matrix_mult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_matrix_mult,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a15t-cpg236-2I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.880000,HLS_SYN_LAT=8,HLS_SYN_TPT=4,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=340,HLS_SYN_LUT=301,HLS_VERSION=2025_1}";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';

    signal Loop_row_proc_U0_ap_start : STD_LOGIC;
    signal Loop_row_proc_U0_ap_done : STD_LOGIC;
    signal Loop_row_proc_U0_ap_continue : STD_LOGIC;
    signal Loop_row_proc_U0_ap_idle : STD_LOGIC;
    signal Loop_row_proc_U0_ap_ready : STD_LOGIC;
    signal Loop_row_proc_U0_A_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal Loop_row_proc_U0_A_ce0 : STD_LOGIC;
    signal Loop_row_proc_U0_A_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal Loop_row_proc_U0_A_ce1 : STD_LOGIC;
    signal Loop_row_proc_U0_B_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal Loop_row_proc_U0_B_ce0 : STD_LOGIC;
    signal Loop_row_proc_U0_B_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal Loop_row_proc_U0_B_ce1 : STD_LOGIC;
    signal Loop_row_proc_U0_AB_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal Loop_row_proc_U0_AB_ce0 : STD_LOGIC;
    signal Loop_row_proc_U0_AB_we0 : STD_LOGIC;
    signal Loop_row_proc_U0_AB_d0 : STD_LOGIC_VECTOR (31 downto 0);

    component matrix_mult_Loop_row_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        A_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        A_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        A_ce1 : OUT STD_LOGIC;
        A_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        B_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        B_ce0 : OUT STD_LOGIC;
        B_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        B_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        B_ce1 : OUT STD_LOGIC;
        B_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        AB_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        AB_ce0 : OUT STD_LOGIC;
        AB_we0 : OUT STD_LOGIC;
        AB_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    Loop_row_proc_U0 : component matrix_mult_Loop_row_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => Loop_row_proc_U0_ap_start,
        ap_done => Loop_row_proc_U0_ap_done,
        ap_continue => Loop_row_proc_U0_ap_continue,
        ap_idle => Loop_row_proc_U0_ap_idle,
        ap_ready => Loop_row_proc_U0_ap_ready,
        A_address0 => Loop_row_proc_U0_A_address0,
        A_ce0 => Loop_row_proc_U0_A_ce0,
        A_q0 => A_q0,
        A_address1 => Loop_row_proc_U0_A_address1,
        A_ce1 => Loop_row_proc_U0_A_ce1,
        A_q1 => A_q1,
        B_address0 => Loop_row_proc_U0_B_address0,
        B_ce0 => Loop_row_proc_U0_B_ce0,
        B_q0 => B_q0,
        B_address1 => Loop_row_proc_U0_B_address1,
        B_ce1 => Loop_row_proc_U0_B_ce1,
        B_q1 => B_q1,
        AB_address0 => Loop_row_proc_U0_AB_address0,
        AB_ce0 => Loop_row_proc_U0_AB_ce0,
        AB_we0 => Loop_row_proc_U0_AB_we0,
        AB_d0 => Loop_row_proc_U0_AB_d0);




    AB_address0 <= Loop_row_proc_U0_AB_address0;
    AB_address1 <= ap_const_lv2_0;
    AB_ce0 <= Loop_row_proc_U0_AB_ce0;
    AB_ce1 <= ap_const_logic_0;
    AB_d0 <= Loop_row_proc_U0_AB_d0;
    AB_d1 <= ap_const_lv32_0;
    AB_we0 <= Loop_row_proc_U0_AB_we0;
    AB_we1 <= ap_const_logic_0;
    A_address0 <= Loop_row_proc_U0_A_address0;
    A_address1 <= Loop_row_proc_U0_A_address1;
    A_ce0 <= Loop_row_proc_U0_A_ce0;
    A_ce1 <= Loop_row_proc_U0_A_ce1;
    A_d0 <= ap_const_lv32_0;
    A_d1 <= ap_const_lv32_0;
    A_we0 <= ap_const_logic_0;
    A_we1 <= ap_const_logic_0;
    B_address0 <= Loop_row_proc_U0_B_address0;
    B_address1 <= Loop_row_proc_U0_B_address1;
    B_ce0 <= Loop_row_proc_U0_B_ce0;
    B_ce1 <= Loop_row_proc_U0_B_ce1;
    B_d0 <= ap_const_lv32_0;
    B_d1 <= ap_const_lv32_0;
    B_we0 <= ap_const_logic_0;
    B_we1 <= ap_const_logic_0;
    Loop_row_proc_U0_ap_continue <= ap_const_logic_1;
    Loop_row_proc_U0_ap_start <= ap_start;
    ap_done <= Loop_row_proc_U0_ap_done;
    ap_idle <= Loop_row_proc_U0_ap_idle;
    ap_ready <= Loop_row_proc_U0_ap_ready;
end behav;
