-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    B_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    B_ce0 : OUT STD_LOGIC;
    B_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    B_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    B_ce1 : OUT STD_LOGIC;
    B_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    AB_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    AB_ce0 : OUT STD_LOGIC;
    AB_we0 : OUT STD_LOGIC;
    AB_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    AB_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    AB_ce1 : OUT STD_LOGIC;
    AB_we1 : OUT STD_LOGIC;
    AB_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matrix_mult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_matrix_mult,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a15t-cpg236-2I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.880000,HLS_SYN_LAT=8,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=398,HLS_SYN_LUT=259,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_20 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000100000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln15_fu_71_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln15_reg_109 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_1_reg_114 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln15_1_fu_85_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln15_1_reg_119 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_reg_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_mult_Pipeline_row_fu_59_ap_start : STD_LOGIC;
    signal grp_matrix_mult_Pipeline_row_fu_59_ap_done : STD_LOGIC;
    signal grp_matrix_mult_Pipeline_row_fu_59_ap_idle : STD_LOGIC;
    signal grp_matrix_mult_Pipeline_row_fu_59_ap_ready : STD_LOGIC;
    signal grp_matrix_mult_Pipeline_row_fu_59_AB_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_mult_Pipeline_row_fu_59_AB_ce0 : STD_LOGIC;
    signal grp_matrix_mult_Pipeline_row_fu_59_AB_we0 : STD_LOGIC;
    signal grp_matrix_mult_Pipeline_row_fu_59_AB_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_mult_Pipeline_row_fu_59_AB_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_mult_Pipeline_row_fu_59_AB_ce1 : STD_LOGIC;
    signal grp_matrix_mult_Pipeline_row_fu_59_AB_we1 : STD_LOGIC;
    signal grp_matrix_mult_Pipeline_row_fu_59_AB_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_mult_Pipeline_row_fu_59_A_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_matrix_mult_Pipeline_row_fu_59_A_ce0 : STD_LOGIC;
    signal grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal B_ce1_local : STD_LOGIC;
    signal B_ce0_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_matrix_mult_Pipeline_row IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        AB_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        AB_ce0 : OUT STD_LOGIC;
        AB_we0 : OUT STD_LOGIC;
        AB_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        AB_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        AB_ce1 : OUT STD_LOGIC;
        AB_we1 : OUT STD_LOGIC;
        AB_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        A_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        tmp_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        empty_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        empty : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_matrix_mult_Pipeline_row_fu_59 : component matrix_mult_matrix_mult_Pipeline_row
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_matrix_mult_Pipeline_row_fu_59_ap_start,
        ap_done => grp_matrix_mult_Pipeline_row_fu_59_ap_done,
        ap_idle => grp_matrix_mult_Pipeline_row_fu_59_ap_idle,
        ap_ready => grp_matrix_mult_Pipeline_row_fu_59_ap_ready,
        AB_address0 => grp_matrix_mult_Pipeline_row_fu_59_AB_address0,
        AB_ce0 => grp_matrix_mult_Pipeline_row_fu_59_AB_ce0,
        AB_we0 => grp_matrix_mult_Pipeline_row_fu_59_AB_we0,
        AB_d0 => grp_matrix_mult_Pipeline_row_fu_59_AB_d0,
        AB_address1 => grp_matrix_mult_Pipeline_row_fu_59_AB_address1,
        AB_ce1 => grp_matrix_mult_Pipeline_row_fu_59_AB_ce1,
        AB_we1 => grp_matrix_mult_Pipeline_row_fu_59_AB_we1,
        AB_d1 => grp_matrix_mult_Pipeline_row_fu_59_AB_d1,
        A_address0 => grp_matrix_mult_Pipeline_row_fu_59_A_address0,
        A_ce0 => grp_matrix_mult_Pipeline_row_fu_59_A_ce0,
        A_q0 => A_q0,
        tmp_1 => tmp_1_reg_114,
        empty_3 => trunc_ln15_reg_109,
        tmp_3 => tmp_3_reg_124,
        empty => trunc_ln15_1_reg_119);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matrix_mult_Pipeline_row_fu_59_ap_ready = ap_const_logic_1)) then 
                    grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_1_reg_114 <= B_q1(63 downto 32);
                tmp_3_reg_124 <= B_q0(63 downto 32);
                trunc_ln15_1_reg_119 <= trunc_ln15_1_fu_85_p1;
                trunc_ln15_reg_109 <= trunc_ln15_fu_71_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_matrix_mult_Pipeline_row_fu_59_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_matrix_mult_Pipeline_row_fu_59_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    AB_address0 <= grp_matrix_mult_Pipeline_row_fu_59_AB_address0;
    AB_address1 <= grp_matrix_mult_Pipeline_row_fu_59_AB_address1;
    AB_ce0 <= grp_matrix_mult_Pipeline_row_fu_59_AB_ce0;
    AB_ce1 <= grp_matrix_mult_Pipeline_row_fu_59_AB_ce1;
    AB_d0 <= grp_matrix_mult_Pipeline_row_fu_59_AB_d0;
    AB_d1 <= grp_matrix_mult_Pipeline_row_fu_59_AB_d1;
    AB_we0 <= grp_matrix_mult_Pipeline_row_fu_59_AB_we0;
    AB_we1 <= grp_matrix_mult_Pipeline_row_fu_59_AB_we1;
    A_address0 <= grp_matrix_mult_Pipeline_row_fu_59_A_address0;
    A_ce0 <= grp_matrix_mult_Pipeline_row_fu_59_A_ce0;
    B_address0 <= ap_const_lv64_1(1 - 1 downto 0);
    B_address1 <= ap_const_lv64_0(1 - 1 downto 0);
    B_ce0 <= B_ce0_local;

    B_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            B_ce0_local <= ap_const_logic_1;
        else 
            B_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_ce1 <= B_ce1_local;

    B_ce1_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            B_ce1_local <= ap_const_logic_1;
        else 
            B_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_matrix_mult_Pipeline_row_fu_59_ap_done)
    begin
        if ((grp_matrix_mult_Pipeline_row_fu_59_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_matrix_mult_Pipeline_row_fu_59_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_matrix_mult_Pipeline_row_fu_59_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_matrix_mult_Pipeline_row_fu_59_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_matrix_mult_Pipeline_row_fu_59_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_matrix_mult_Pipeline_row_fu_59_ap_start <= grp_matrix_mult_Pipeline_row_fu_59_ap_start_reg;
    trunc_ln15_1_fu_85_p1 <= B_q0(32 - 1 downto 0);
    trunc_ln15_fu_71_p1 <= B_q1(32 - 1 downto 0);
end behav;
